global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h
  receiver: 'webhook-logger'

receivers:
  - name: 'webhook-logger'
    webhook_configs:
      - url: 'http://webhook-logger:5001/'
        send_resolved: true
